Vagrant.configure("2") do |config|
    config.vm.define "inetRouter" do |vm1|
    vm1.vm.box = "centos/7"
    vm1.vm.network "private_network", auto_config: false, virtualbox__intnet: "router-net", adapter: 2
    vm1.vm.network "private_network", auto_config: false, virtualbox__intnet: "router-net", adapter: 3
    vm1.vm.network "private_network", ip: "192.168.56.10", adapter: 8
    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
       end
    vm1.vm.provision :shell, inline: "hostname inetRouter"
    end
    config.vm.define "centralRouter" do |vm2|
    vm2.vm.box = "centos/7"    
    vm2.vm.network "private_network", auto_config: false, virtualbox__intnet: "router-net", adapter: 2
    vm2.vm.network "private_network", auto_config: false, virtualbox__intnet: "router-net", adapter: 3   
    vm2.vm.network "private_network", ip: "192.168.255.9", netmask: "255.255.255.252", auto_config: false, virtualbox__intnet: "office1-central", adapter: 6
    vm2.vm.network "private_network", ip: "192.168.56.11", adapter: 8
    vm2.vm.provision :shell, inline: "hostname centralRouter"
    end
    config.vm.define "office1Router" do |vm3|
    vm3.vm.box = "centos/7"
    vm3.vm.network "private_network", ip: "192.168.255.10", netmask: "255.255.255.252", auto_config: false, virtualbox__intnet: "office1-central", adapter: 2
    vm3.vm.network "private_network", auto_config: false, virtualbox__intnet: "vlan1", adapter: 3  
    vm3.vm.network "private_network", auto_config: false, virtualbox__intnet: "vlan1", adapter: 4
    vm3.vm.network "private_network", auto_config: false, virtualbox__intnet: "vlan2", adapter: 5
    vm3.vm.network "private_network", auto_config: false, virtualbox__intnet: "vlan2", adapter: 6
    vm3.vm.network "private_network", ip: "192.168.56.20", adapter: 8
    vm3.vm.provision :shell, inline: "hostname office1Router"
    end
    config.vm.define "testClient1" do |vm4|
    vm4.vm.box = "centos/7"
    vm4.vm.network "private_network", auto_config: false, virtualbox__intnet: "testLAN", adapter: 2
    vm4.vm.network "private_network", ip: "192.168.56.21", adapter: 8
    vm4.vm.provision :shell, inline: "hostname testClient1"
    end  
    config.vm.define "testServer1" do |vm5|
    vm5.vm.box = "centos/7"
    vm5.vm.network "private_network", auto_config: false, virtualbox__intnet: "testLAN", adapter: 2
    vm5.vm.network "private_network", ip: "192.168.56.22", adapter: 8
    vm5.vm.provision :shell, inline: "hostname testServer1"
    end      
    config.vm.define "testClient2" do |vm6|
    vm6.vm.box = "generic/ubuntu2204"
    vm6.vm.network "private_network", auto_config: false, virtualbox__intnet: "testLAN", adapter: 2
    vm6.vm.network "private_network", ip: "192.168.56.31", adapter: 8
    vm6.vm.provision :shell, inline: "hostname testClient2"
    end  
    config.vm.define "testServer2" do |vm7|
    vm7.vm.box = "generic/ubuntu2204"
    vm7.vm.network "private_network", auto_config: false, virtualbox__intnet: "testLAN", adapter: 2
    vm7.vm.network "private_network", ip: "192.168.56.32", adapter: 8
    vm7.vm.provision :shell, inline: "hostname testServer2"
    end    
end