# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.box_version = "2004.01"
    config.vm.box_check_update = false
    config.vm.provider "virtualbox" do |vb|
       vb.memory = "1024"
       vb.cpus = 4
    end
    config.vm.define "backup" do |backup|
      backup.vm.network "private_network", ip: '192.168.11.160', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "netnfs"
      backup.vm.network :forwarded_port, guest: 22, host: 2201, id: "ssh"
      backup.vm.hostname = "backup.local"
      
    end
    config.vm.define "client" do |client|
      client.vm.network "private_network", ip: '192.168.11.150', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "netnfs"
      client.vm.network :forwarded_port, guest: 22, host: 2202, id: "ssh"
      client.vm.hostname = "client.local"
        
    end
end