# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINES = {
  :dynweb => {
    :box_name => "centos/7",
    :vm_name => "dynweb",
    :ip => '192.168.50.10', # for ansible
    :mem => '2048',
    :cpus => '2'
  }
}
Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      box.vm.network "private_network", ip: boxconfig[:ip]
      box.vm.network "forwarded_port", guest: 8081, host: 8081
      box.vm.network "forwarded_port", guest: 8082, host: 8082
      box.vm.network "forwarded_port", guest: 8083, host: 8083
      box.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", boxconfig[:mem]]
        vb.customize ["modifyvm", :id, "--cpus", boxconfig[:cpus]]
      end
#      if boxconfig[:vm_name] == "dynweb"
#        box.vm.provision "ansible" do |ansible|
#          ansible.playbook = "ansible/playbook.yml"
#          ansible.inventory_path = "ansible/hosts"
#          ansible.become = true
#          ansible.host_key_checking = "false"
#          ansible.limit = "all"
#          ansible.verbose = "vvv"
#        end
#      end
    end
  end
end