# Описываем Виртуальные машины
MACHINES = {
  # Указываем имя ВМ "kernel update"
  :"centos7raid" => {
              #Какой vm box будем использовать
              :box_name => "centos/7",
              #Указываем box_version
              :box_version => "2004.01",
              #Указываем количество ядер ВМ
              :cpus => 2,
              #Указываем количество ОЗУ в мегабайтах
              :memory => 1024,
              :disks => {
		                  :sata1 => {
			                        :dfile => './VM/hdd/sata1.vdi',
			                        :size => 1024*10,
			                        :port => 1
		                  },
                      :sata2 => {
                              :dfile => './VM/hdd/sata2.vdi',
                              :size => 1024*10, # Megabytes
                              :port => 2
                      },
		                  :sata3 => {
			                        :dfile => './VM/hdd/sata3.vdi',
			                        :size => 1024*10, 
			                        :port => 3
		                  },
		                  :sata4 => {
		                          :dfile => './VM/hdd/sata4.vdi',
			                        :size => 1024*10,
			                        :port => 4
                      }
               }
    }
}            
Vagrant.configure("2") do |config|
 
  MACHINES.each do |boxname, boxconfig|
    # Отключаем проброс общей папки в ВМ
    config.vm.synced_folder ".", "/vagrant", disabled: true
    # Применяем конфигурацию ВМ
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name = boxname.to_s
      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
        v.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
        boxconfig[:disks].each do |diskname, diskconf|
             unless File.exist?(diskconf[:dfile])
                     v.customize ["createmedium", "disk", "--filename", diskconf[:dfile], "--format", "vdi", "--size", diskconf[:size]]
             end
        v.customize ["storageattach", :id, "--storagectl", "SATA", "--port", diskconf[:port], "--device", 0, "--type", "hdd", "--medium", diskconf[:dfile]]
        end
      box.vm.provision "shell", path: "./initraid.sh"  
      end
    end
  end
end

